### ISSUE TITLE
Implement the Functional Logic of the Dataset Browse Page

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#44]
As a user of the TDC portal, I want to search for datasets related to specific keywords and apply various filters, so that I can easily find and access relevant data.

## Tasklist (TBD - to be updated by the developer)
* [add task]

## Acceptance Criteria
Given that I am on the data portal
* [ ] i can view a page with the same functionality and behaviour as this [figma design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=12-20858&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)
* [ ] i can search for datasets by entering keywords in the search bar and see relevant results.
* [ ] i can apply filters and sort the results to narrow down search results.
* [ ] i can use quick filters to easily apply common filters with a single click.
* [ ] i can clear all filters and the keyword in the search bar.

**Comment by Gutts-n** [comment]
Questions:

Will these filters work as CKAN? CKAN displays just the filter with datasets linked with it, and when it selects a specific filter it limits the other filters together aggregating it. 

e.g.: organization **X** has 1 dataset with the tag **Y** when selected organization **X** it will hide any other tags from the filters because there is just one tag related to this organization.

![Image](https://github.com/user-attachments/assets/3bd3ddde-f16f-4d66-91ed-53568b78abac)
![Image](https://github.com/user-attachments/assets/5cf97aa6-58d0-4fba-adbe-492691206b7a)

Another point is, why do we have a region filter on top and another one inside of the locations filter? If it's the proposal how should it work?

![Image](https://github.com/user-attachments/assets/c4ffc316-2983-40ca-8152-9486b6142cd9)

cc: @osahon-okungbowa @Uchechukwu-Onye-Igbo

**Comment by osahon-okungbowa** [comment]
we paused work on this to focus on the Geography page

**Comment by Gutts-n** [comment]
How would this quick filter work if I filter for multiple regions? 

![Image](https://github.com/user-attachments/assets/c2d119ad-c870-446d-8ec2-cbf3183db58a)

e.g.: Filtered by Asia and Europe

Will we select multiple regions in the quick filter as well changing the radio input into a multiple radio input (the user can select multiple bullet items instead of just one)?

cc: @Uchechukwu-Onye-Igbo and @osahon-okungbowa

**Comment by Uchechukwu-Onye-Igbo** [comment]
#Feedback on the Advanced Filter Implementation

* Remove the search bar at the top of the advanced filter pane
* A toggle to hide and show the advanced filter should be added in the space between region and sort in the quick filter bar
* Clear filter should be added into all the filters in the facet
* Years covered: 
  * from and to to be done using range - remove the checklists. 
  * There should be a clear button for the dates as well. 
  * There should be a button by the side that says "go" after the dates are entered and user is ready to search
* Publication date: 
  * Show all options by default. 
  * Update the count of available result based on the number of years selected. 
  * If the dates selected have no values, tell the user 0.
  * Show the user how many of the options in a given filter accordion selected

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo and @osahon-okungbowa I believe they should be checkboxes as the regions because they are multi-select as well:

![Image](https://github.com/user-attachments/assets/c288cad6-72b5-48dd-9e86-a20030533cbf)

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Feedback on the Browse Page

Bugs:

* The "Water_transportation" filter label: Is this the dataset name or the filter label? It should be "Water Transportation." If the database has the correct label and it's still showing incorrectly, this is a bug.
* The dataset says "Europe," but selecting "Europe" in the region filter doesn’t work. Example dataset: "Goods transported by type of transport." Check if this issue originates from the dataset or the frontend.
* Regarding the years covered in the filter, are they being pulled from the available datasets or generated sequentially? For example, If we want the "to" year to be only 2002, it's currently not an option because the "from" has already been set to 2002. If the years are sequenced by the calendar, allow the "from" and "to" years to be the same so that the user can search for data within the same year.

Improvement:

* The number of results should be displayed below the quick filter at the top of the page and should dynamically update whenever the filter changes the result, just like how it's shown in the advanced filter.
* Note: when you return this issue to QA, add links to the documentation and integration tests.

@Gutts-n

**Comment by Gutts-n** [comment]
Link to the doc: https://github.com/transport-data/tdc-data-portal/blob/main/docs/datasets/README.md

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback

Hello @Gutts-n, please attend to this point;
- - Year filter works but when you select location, it fails to work. the results showing up says Europe but if you select Europe in regions, it does not show any result. The location filters work if year filter is not applied.

**Comment by Uchechukwu-Onye-Igbo** [comment]
> ### QA Feedback
> Hello [@Gutts-n](https://github.com/Gutts-n), please attend to this point;
> 
> * Year filter works but when you select location, it fails to work. the results showing up says Europe but if you select Europe in regions, it does not show any result. The location filters work if year filter is not applied.
> * When the from and to fields of years covered is set to 2024 and 2024, it returns only 2 datasets. but when cleared, you can see over 100 datasets relating to 2024. Hint; this happens when you select after 2024 first from the search bar and then update "to" to 2024 in the browse page

this has been fixed. thanks @Gutts-n

**Comment by nicolas-becker** [comment]
As widely discussed, this looks good now, thank you! 

Just one minor request: The "years covered" dropdown window is much bigger than the other filters.

![Image](https://github.com/user-attachments/assets/b83a1476-13c3-4a7c-9aea-ea66f30883c1)

It would look nicer if all the filters are of the same size (e.g. in terms of font size). Would that be possible to adapt?

**Comment by Gutts-n** [comment]
@nicolas-becker thank you for the feedback.

I noticed that the font size of the clear filter was bigger than the other filters and changed it.

I can do it this way to reduce the size:

![Image](https://github.com/user-attachments/assets/8c7efe7a-b51a-4dd0-9d1c-c6d298ce6db2)

Or to leave it horizontal I can reduce the size of each input and move down the search button:

![Image](https://github.com/user-attachments/assets/50b9107a-e1b9-43d3-a1de-f6e68aebd9ae)

What do you prefer?

**Comment by nicolas-becker** [comment]
Thanks for your reply! I prefer keeping the horizontal view. Maybe also try to have the 'Search' and 'Clear filter' buttons in the same format?

**Comment by Gutts-n** [comment]
@nicolas-becker I think I didn't get what you are referring to. Do you mean to both be bold text?

**Comment by nicolas-becker** [comment]
@Gutts-n At first sight it looked like also the font size was different. But if the only difference is the text being bold in one option, then yes please. Thank you Leonardo

**Comment by Gutts-n** [comment]
@nicolas-becker I pushed the changes to the page, take a look and give me feedback, pls.

**Comment by nicolas-becker** [comment]
@Gutts-n Thanks for the adaptation, looks better now. Would it be possible to also reduce the size of the input fields (From/To)? They still appear a bit oversized. 

![image](https://github.com/user-attachments/assets/572661e9-1fa0-4e80-9744-2e31f30443c2)
 
Also I just noticed that the years for selection start at 2099. Is there a quick fix to limit the selection period to the current year? 

Thanks!

**Comment by Gutts-n** [comment]
Hey @nicolas-becker I left the size of the inputs this way because it's the minimum size to present the entire year without losing a number of the year:

![Image](https://github.com/user-attachments/assets/83e17c5a-57e7-4245-aa85-2215ce7b21b1)


If we reduced the size:

![Image](https://github.com/user-attachments/assets/da51e675-624e-470c-aaeb-c390266a5436)

About the 2099 it is not happening to me:

![Image](https://github.com/user-attachments/assets/dbe3d532-65bc-4f75-b3f2-78711b79f426)

![Image](https://github.com/user-attachments/assets/fb77d1c7-79c4-4d4a-9826-a7916e382b55)

**Comment by nicolas-becker** [comment]
Hi Leonardo, thanks for getting back in this this quickly. I understand the issue, thanks for the explanation. If it is not possible to reduce the font size of the year, than it's fine to leave it this way. 

Regarding the year selection, 2024 is also appearing as default to me, that is fine. My question was directed towards whether it is possible to reduce the selection period to years up to the current year, to deflate the amount of options displayed. But this again is just a minor issue

@Gutts-n

**Comment by Gutts-n** [comment]
@nicolas-becker which year do you think would be great to be the limit?

About the font size I'll take a look to see if I can change it as it is a component from an external lib I don't have access to change the style of the component, but I'll try to change it.

**Comment by nicolas-becker** [comment]
@Gutts-n as the user should only be able to select years from the past, which are actually reflected in the data, it would be great if the selection period could dynamically adapt to the current year. But I understand if this might not be (or only hardly) possible, in which case we can leave it like this.

Also thanks for the clarification regarding the external lib. Please let me know if you will be able to do any more modifications, otherwise I'll move the issue to done. Thanks!

**Comment by Gutts-n** [comment]
@nicolas-becker I pushed a fix to the font size of the component take a look and give me feedback.

**Comment by nicolas-becker** [comment]
Great, thanks!

**Comment by nicolas-becker** [comment]
Hi @Gutts-n I've just noticed two more unexpected behaviours on the page:

- The page selection initially shows only 3 pages but expands when moving the page (see video 1):

https://github.com/user-attachments/assets/199533a1-cb0f-4c52-ab5f-0522007dbde0

- the clickable area of the entries is a lot bigger than expected (see video 2):

https://github.com/user-attachments/assets/5c0ff4da-1a40-4e2a-ba35-f8aff28dfb56

Both behaviours have been experienced e.g. here: https://tdc-data-portal.vercel.app/search?region=worldwide&query=

**Comment by Gutts-n** [comment]
@nicolas-becker I pushed a fix, please take a look and give me feedback.

**Comment by nicolas-becker** [comment]
@Gutts-n Thanks, both issues work now

**Comment by nicolas-becker** [comment]
Hi @Gutts-n , I just noticed a new bug on the dataset browse page. I was revising the datasets on ATO created by Meiran and filtered for ATO as org.

![image](https://github.com/user-attachments/assets/e3e95863-8479-492e-80ee-e5c95dc25d77)

I get 61 results, but I can see only 9 of them. 
![image](https://github.com/user-attachments/assets/9f30210a-666b-41c8-84d6-9c83ef3ecb4f)

After a while I've noticed that the page selection appears at the bottom of the page, for some reason.
![image](https://github.com/user-attachments/assets/030707b7-7c61-4864-915c-714a4f00aa5a)

Any idea why this could be happening? I will let you know if I experience the issue in some other case. Thanks!

**Comment by Gutts-n** [comment]
@nicolas-becker it's paginated, there are 61 datasets but you will see 9 on each page. I'll check what is happening with this blank space between the datasets cards and the pagination.

**Comment by nicolas-becker** [comment]
@Gutts-n I understand. I was rather wondering why the pagination was not appearing until I found it at the bottom of the page. Thanks for having a look!

**Comment by Gutts-n** [comment]
@nicolas-becker fixed, I changed to the pagination be close to the cards instead of fixed at the bottom of the page (it wasn't necessarily a bug, it happened because you clicked to show all the organizations of the portal, and when you did it the organization filter expanded increasing the height of the page with it, as the pagination was fixed to be at the bottom of the page it happened 👍 ).

**Comment by nicolas-becker** [comment]
Understood, works much better now, thanks!
